### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by dhasenan** [ClassicThunder/MonoGameGui#1]
There's no license documented for this project. As such, it would be illegal for me to include it in my game if I intend to share it with anyone. While MonoGameGui seems to be a descendant of Ruminate (https://xnagui.codeplex.com/), which is under the MIT license, it contains modifications, and those are not necessarily under the same license (especially as you seem to be the original author and can relicense your code at will).

This is kind of a barrier to usage.

**Comment by ClassicThunder** [comment]
Added licencing information to both of the projects. Both remain under MIT. I'm not planning to work on the project or support it. In the future (probably starting November) an updated version will likely be moved into the [MonoGame.Extended](https://github.com/craftworkgames/MonoGame.Extended) library which I have been contributing to when I have the spare time. You can find an updated version of the event driven input contained in this library there.
